In [3]:
# LIBRARIES
import os
import json
import pandas as pd
import pymysql
import geopandas

In [4]:
# AGGREGATE TRANSACTIONS

path_agg_trans = "C:/Users/muthu/Desktop/guvi project/capstone 2 Phonepe/pulse/data/aggregated/transaction/country/india/state"
Agg_trans_state_list = os.listdir(path_agg_trans)
# Agg_trans_state_list

columns_agg_trans={'States':[], 'Year':[],'Quarter':[],'Transaction_Type':[], 'Transaction_Count':[], 'Transaction_Amount':[]}
for i_state in Agg_trans_state_list:
    states = path_agg_trans+"/"+i_state+"/"
    # print(states)
    Agg_trans_year = os.listdir(states)
    
    for j_year in Agg_trans_year:
        Agg_T_year_list=states+j_year+"/"
        Agg_year_details=os.listdir(Agg_T_year_list)
        
        for k_year in Agg_year_details:
            inside_Year=Agg_T_year_list+k_year
            data=open(inside_Year,'r')
            year_data=json.load(data)
            
            for z_year in year_data['data']['transactionData']:
                Name=z_year['name']
                count=z_year['paymentInstruments'][0]['count']
                amount=z_year['paymentInstruments'][0]['amount']
                columns_agg_trans['Transaction_Type'].append(Name)
                columns_agg_trans['Transaction_Count'].append(count)
                columns_agg_trans['Transaction_Amount'].append(amount)
                columns_agg_trans['States'].append(i_state)
                columns_agg_trans['Year'].append(j_year)
                columns_agg_trans['Quarter'].append(int(k_year.strip('.json')))

Aggregated_Trans = pd.DataFrame(columns_agg_trans) 
Aggregated_Trans['States']=Aggregated_Trans['States'].str.title() 
Aggregated_Trans['States']=Aggregated_Trans['States'].str.replace("-"," ")              
# Aggregated_Trans

In [5]:
# AGGREGATED USERS

path_agg_users = "C:/Users/muthu/Desktop/guvi project/capstone 2 Phonepe/pulse/data/aggregated/user/country/india/state"
Agg_user_state_list = os.listdir(path_agg_users)
# Agg_user_state_list

columns_agg_users={'States':[], 'Year':[],'Quarter':[],'Brands':[], 'Count':[], 'Percentage':[]}
for i_state in Agg_user_state_list:
    states=path_agg_users+"/"+i_state+"/"
    Agg_users_year=os.listdir(states)
    
    for j_year in Agg_users_year:
        Agg_U_year_list=states+j_year+"/"
        Agg_year_users=os.listdir(Agg_U_year_list)
        
        for k_year in Agg_year_users:
            inside_Year=Agg_U_year_list+k_year
            data=open(inside_Year,'r')
            year_data=json.load(data)
            
            try:
                for z_year in year_data['data']['usersByDevice']:
                    Brand=z_year['brand']
                    Count=z_year['count']
                    Percentage=z_year['percentage']
                    columns_agg_users['Brands'].append(Brand)
                    columns_agg_users['Count'].append(Count)
                    columns_agg_users['Percentage'].append(Percentage)
                    columns_agg_users['States'].append(i_state)
                    columns_agg_users['Year'].append(j_year)
                    columns_agg_users['Quarter'].append(int(k_year.strip('.json')))
            except:
                pass
Aggregated_Users=pd.DataFrame(columns_agg_users)
Aggregated_Users['States']=Aggregated_Users['States'].str.title() 
Aggregated_Users['States']=Aggregated_Users['States'].str.replace("-"," ")       
# Aggregated_Users

In [6]:
# MAP TRANSACTIONS

path_map_trans = "C:/Users/muthu/Desktop/guvi project/capstone 2 Phonepe/pulse/data/map/transaction/hover/country/india/state"
map_trans_state_list = os.listdir(path_map_trans)
# map_trans_state_list

columns_map_trans={'States':[], 'Year':[],'Quarter':[],'District_Name':[], 'Transaction_Count':[], 'Transaction_Amount':[]}
for i_state in map_trans_state_list:
    states = path_map_trans+"/"+i_state+"/"
    # print(states)
    map_trans_year = os.listdir(states)
    
    for j_year in map_trans_year:
        map_T_year_list=states+j_year+"/"
        map_year_details=os.listdir(map_T_year_list)
        
        for k_year in map_year_details:
            inside_Year=map_T_year_list+k_year
            data=open(inside_Year,'r')
            year_data=json.load(data)
            
            for z_year in year_data['data']['hoverDataList']:
                Name=z_year['name']
                count=z_year['metric'][0]['count']
                amount=z_year['metric'][0]['amount']
                columns_map_trans['District_Name'].append(Name)
                columns_map_trans['Transaction_Count'].append(count)
                columns_map_trans['Transaction_Amount'].append(amount)
                columns_map_trans['States'].append(i_state)
                columns_map_trans['Year'].append(j_year)
                columns_map_trans['Quarter'].append(int(k_year.strip('.json')))
Map_Transactions= pd.DataFrame(columns_map_trans)
Map_Transactions['States']=Map_Transactions['States'].str.title() 
Map_Transactions['States']=Map_Transactions['States'].str.replace("-"," ") 
# Map_Transactions

In [7]:
path_map_users = "C:/Users/muthu/Desktop/guvi project/capstone 2 Phonepe/pulse/data/map/user/hover/country/india/state"
map_users_state_list = os.listdir(path_map_users)
# map_users_state_list

columns_map_users={'States':[], 'Year':[],'Quarter':[],'District_Name':[], 'RegisteredUsers':[], 'AppOpens':[]}
for i_state in map_users_state_list:
    states = path_map_users+"/"+i_state+"/"
    # print(states)
    map_users_year = os.listdir(states)
    
    for j_year in map_users_year:
        map_U_year_list=states+j_year+"/"
        map_year_details=os.listdir(map_U_year_list)
        
        for k_year in map_year_details:
            inside_Year=map_U_year_list+k_year
            data=open(inside_Year,'r')
            year_data=json.load(data)
            
            for z_year in year_data['data']['hoverData'].items():
                district=z_year[0]
                registeredusers=z_year[1]['registeredUsers']
                appopens=z_year[1]['appOpens']
                columns_map_users['District_Name'].append(district)
                columns_map_users['RegisteredUsers'].append(registeredusers)
                columns_map_users['AppOpens'].append(appopens)
                columns_map_users['States'].append(i_state)
                columns_map_users['Year'].append(j_year)
                columns_map_users['Quarter'].append(int(k_year.strip('.json')))
Map_Users=pd.DataFrame(columns_map_users)
Map_Users['States']=Map_Users['States'].str.title() 
Map_Users['States']=Map_Users['States'].str.replace("-"," ")
# Map_Users

In [8]:
# TOP TRANSACTIONS

path_top_trans = "C:/Users/muthu/Desktop/guvi project/capstone 2 Phonepe/pulse/data/top/transaction/country/india/state"
top_trans_state_list = os.listdir(path_top_trans)
# top_trans_state_list

columns_top_trans={'States':[], 'Year':[],'Quarter':[],'Pincodes':[], 'Transaction_Count':[], 'Transaction_Amount':[]}
for i_state in top_trans_state_list:
    states = path_top_trans+"/"+i_state+"/"
    # print(states)
    top_trans_year = os.listdir(states)
    
    for j_year in top_trans_year:
        top_T_year_list=states+j_year+"/"
        top_year_details=os.listdir(top_T_year_list)
        
        for k_year in top_year_details:
            inside_Year=top_T_year_list+k_year
            data=open(inside_Year,'r')
            year_data=json.load(data)
            
            for z_year in year_data['data']['pincodes']:
                entitynames=z_year['entityName']
                count=z_year['metric']['count']
                amount=z_year['metric']['amount']
                columns_top_trans['Pincodes'].append(entitynames)
                columns_top_trans['Transaction_Count'].append(count)
                columns_top_trans['Transaction_Amount'].append(amount)
                columns_top_trans['States'].append(i_state)
                columns_top_trans['Year'].append(j_year)
                columns_top_trans['Quarter'].append(int(k_year.strip('.json')))
Top_Transactions=pd.DataFrame(columns_top_trans)
Top_Transactions['States']=Top_Transactions['States'].str.title() 
Top_Transactions['States']=Top_Transactions['States'].str.replace("-"," ")
# Top_Transactions

In [9]:
# TOP USERS

path_top_users = "C:/Users/muthu/Desktop/guvi project/capstone 2 Phonepe/pulse/data/top/user/country/india/state"
top_users_state_list = os.listdir(path_top_users)
# top_users_state_list

columns_top_users={'States':[], 'Year':[],'Quarter':[],'Pincodes':[], 'RegisteredUsers':[]}
for i_state in top_users_state_list:
    states = path_top_users+"/"+i_state+"/"
    # print(states)
    top_users_year = os.listdir(states)
    
    for j_year in top_users_year:
        top_U_year_list=states+j_year+"/"
        top_year_details=os.listdir(top_U_year_list)
        
        for k_year in top_year_details:
            inside_Year=top_U_year_list+k_year
            data=open(inside_Year,'r')
            year_data=json.load(data)
            
            for z_year in year_data['data']['pincodes']:
                name=z_year['name']
                registeredusers=z_year['registeredUsers']
                columns_top_users['Pincodes'].append(name)
                columns_top_users['RegisteredUsers'].append(registeredusers)
                columns_top_users['States'].append(i_state)
                columns_top_users['Year'].append(j_year)
                columns_top_users['Quarter'].append(int(k_year.strip('.json')))
Top_Users=pd.DataFrame(columns_top_users)
Top_Users['States']=Top_Users['States'].str.title() 
Top_Users['States']=Top_Users['States'].str.replace("-"," ")
# Top_Users

In [10]:
# 1_SQL TABLE AAGGREGATED TRANSACTIONS
myconnection=pymysql.connect(host='127.0.0.1',user='root',password='admin',database="phonepedata",port=3306)
cur=myconnection.cursor()

table_1='''create table if not exists aggregated_transactions(States varchar(100),
                                                Year YEAR,
                                                Quarter int,
                                                Transaction_Type varchar(100),
                                                Transaction_Count bigint,
                                                Transaction_Amount bigint)'''
cur.execute(table_1)
myconnection.commit()

for index,row in Aggregated_Trans.iterrows():
    insert_table_1='''insert into aggregated_transactions(States, Year, Quarter, Transaction_Type, Transaction_Count, Transaction_Amount)
                                                            values(%s,%s,%s,%s,%s,%s)'''
                                                            
    values=(row['States'], row['Year'], row['Quarter'], row['Transaction_Type'], row['Transaction_Count'], row['Transaction_Amount'])
    cur.execute(insert_table_1,values)
myconnection.commit()

In [11]:
# 2_SQL TABLE AAGGREGATED USERS
myconnection=pymysql.connect(host='127.0.0.1',user='root',password='admin',database="phonepedata",port=3306)
cur=myconnection.cursor()

table_2='''create table if not exists aggregated_users(States varchar(100),
                                                    Year YEAR,
                                                    Quarter int,
                                                    Brand varchar(100),
                                                    Count bigint,
                                                    Percentage float)'''
cur.execute(table_2)
myconnection.commit()

for index,row in Aggregated_Users.iterrows():
    insert_table_2='''insert into aggregated_users(States, Year, Quarter, Brand, Count, Percentage)
                                                    values(%s,%s,%s,%s,%s,%s)'''
                                                    
    values=(row['States'], row['Year'], row['Quarter'], row['Brands'], row['Count'], row['Percentage'])
    cur.execute(insert_table_2,values)
myconnection.commit()

In [12]:
# 3_SQL TABLE MAP TRANSACTIONS
myconnection=pymysql.connect(host='127.0.0.1',user='root',password='admin',database="phonepedata",port=3306)
cur=myconnection.cursor()

table_3='''create table if not exists map_transactions(States varchar(100),
                                                    Year YEAR,
                                                    Quarter int,
                                                    District_Name varchar(50),
                                                    Transaction_count bigint,
                                                    Transaction_Amount float)'''
cur.execute(table_3)
myconnection.commit()

for index,row in Map_Transactions.iterrows():
    insert_table_3='''insert into map_transactions(States, Year, Quarter, District_Name, Transaction_Count, Transaction_Amount)
                                                            values(%s,%s,%s,%s,%s,%s)'''
                                                            
    values=(row['States'], row['Year'], row['Quarter'], row['District_Name'], row['Transaction_Count'], row['Transaction_Amount'])
    cur.execute(insert_table_3,values)
myconnection.commit()

In [13]:
# 4_SQL TABLE MAP USERS
myconnection=pymysql.connect(host='127.0.0.1',user='root',password='admin',database="phonepedata",port=3306)
cur=myconnection.cursor()

table_4='''create table if not exists map_users(States varchar(100),
                                                Year YEAR,
                                                Quarter int,
                                                District_Name varchar(50),
                                                RegisteredUsers bigint,
                                                AppOpens bigint)'''
cur.execute(table_4)
myconnection.commit()

for index,row in Map_Users.iterrows():
    insert_table_4='''insert into map_users(States, Year, Quarter, District_Name, RegisteredUsers, AppOpens)
                                            values(%s,%s,%s,%s,%s,%s)'''
                                            
    values=(row['States'], row['Year'], row['Quarter'], row['District_Name'], row['RegisteredUsers'], row['AppOpens'])
    cur.execute(insert_table_4,values)
myconnection.commit()

In [14]:
# 5_SQL TABLE TOP TRANSACTIONS

myconnection=pymysql.connect(host='127.0.0.1',user='root',password='admin',database="phonepedata",port=3306)
cur=myconnection.cursor()

table_5='''create table if not exists top_transactions(States varchar(100), Year YEAR, Quarter int, Pincodes int, Transaction_Count bigint, Transaction_Amount bigint)'''
cur.execute(table_5)
myconnection.commit()

for index,row in Top_Transactions.iterrows():
    insert_table_5='''insert into top_transactions(States, Year, Quarter, Pincodes, Transaction_Count, Transaction_Amount)
                                                    values(%s,%s,%s,%s,%s,%s)'''
    values=(row['States'], row['Year'], row['Quarter'], row['Pincodes'], row['Transaction_Count'], row['Transaction_Amount'])
    cur.execute(insert_table_5,values)
myconnection.commit()

In [15]:
# 6_SQL TABLE TOP USERS
myconnection=pymysql.connect(host='127.0.0.1',user='root',password='admin',database="phonepedata",port=3306)
cur=myconnection.cursor()

table_6='''create table if not exists top_users(States varchar(100), Year YEAR, Quarter int, Pincodes int, Registered_Users bigint)'''
cur.execute(table_6)
myconnection.commit()

for index,row in Top_Users.iterrows():
    insert_table_6='''insert into top_users(States, Year, Quarter, Pincodes, Registered_Users)
                                            values(%s,%s,%s,%s,%s)'''
    values=(row['States'], row['Year'], row['Quarter'], row['Pincodes'], row['RegisteredUsers'])
    cur.execute(insert_table_6,values)
myconnection.commit()